# Generated by Django 4.1.6 on 2023-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('entry', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=30)),
            ],
        ),
    ]
